spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  application:
    name: jiahe-px-controller
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  datasource:
    username: sa
    password: myshopr5
    url: jdbc:sqlserver://172.16.120.1:1077;DatabaseName=test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #sql执行超时时间,单位秒
    default-statement-timeout: 25
    #驼峰命名
    map-underscore-to-camel-case: false
  type-aliases-package: com.jiahe.px.mybatis.dao

server:
  #当前服务端口号
  port: 9762
  tomcat:
    uri-encoding: UTF-8
#    max-http-header-size: 1073741824



jetcache:
  # 统计间隔，默认0：表示不统计
  statIntervalMinutes: 1
  # areaName是否作为缓存key前缀，默认True
  areaInCacheName: false
  local:
    default:
      # 已支持可选：linkedhashmap、caffeine
      type: linkedhashmap
      # key转换器的全局配置，当前只有：fastjson, @see com.alicp.jetcache.support.FastjsonKeyConvertor
      keyConvertor: fastjson
      # 每个缓存实例的最大元素的全局配置，仅local类型的缓存需要指定
      limit: 100
      # jetcache2.2以上，以毫秒为单位，指定多长时间没有访问，就让缓存失效，当前只有本地缓存支持。0表示不使用这个功能
      expireAfterAccessInMillis: 30000
#  remote:
#    default:
#      # 已支持可选：redis、tair
#      type: redis.lettuce
#      # 连接格式@see：https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details
#      uri: redis://localhost:6379/1?timeout=5s
#      keyConvertor: fastjson
#      # 序列化器的全局配置。仅remote类型的缓存需要指定，可选java和kryo
#      valueEncoder: java
#      valueDecoder: java
#      # 以毫秒为单位指定超时时间的全局配置
#      expireAfterWriteInMillis: 5000

px:
  url: https://pxq.dazhang.net.cn
  appId: 290276824989040640
  appSecret: 151f311e26bc4d1281313adda90d6422
  customNo:  0000601250
